Make TaggableManager.set API compatible with Django's RelatedManager.set
jazzband/django-taggit pull request #763
Opened 2021-11-09 16:27 UTC by pablolmedorado

See #686

2021-11-10 05:59 UTC, auvipy requested changes
please fix the conflicts and rebase issues

2021-11-10 06:04 UTC, auvipy commented on docs/api.rst
> +    .. method:: set(tags, through_defaults=None, clear=False)
def set(self, tags, *, through_defaults=None, **kwargs) has separate *

2021-11-10 06:52 UTC, pablolmedorado commented on docs/api.rst
> +    .. method:: set(tags, through_defaults=None, clear=False)
Done! Nice spot

2021-11-10 08:05 UTC, rtpg commented
I don't consider this a blocker but I think it would be good if the release notes just went into more detail, saying that this changed from taking varargs to taking an explicit list (perhaps just an example). Without that people will have to dig into the code to figure out what change is needed here.

2021-11-10 08:26 UTC, pablolmedorado commented
I agree and am willing to change it. The reason why I have not done it from the beginning is because I am not very confident in my level of English. It is my first pull request and I did not know how to proceed.

If you want, I could try to explain it and, if you think there is a better translation, you can correct me.

Best regards.

2021-11-10 11:24 UTC, auvipy commented
> I agree and am willing to change it. The reason why I have not done it from the beginning is because I am not very confident in my level of English. It is my first pull request and I did not know how to proceed.
> 
> If you want, I could try to explain it and, if you think there is a better translation, you can correct me.
> 
> Best regards.

sure please

2021-11-10 11:30 UTC, rtpg commented
@pablolmedorado that sounds good, yes! It doesn't have to be very long, just a bit more details (given this would be a backwards incompatible change)

Given that it's been a while since the last release, I think once this is cleaned up we can package up a release

2021-11-11 09:06 UTC, pablolmedorado commented
I've updated the changelog according to what you pointed out yesterday. Feel free to modify anything you consider wrong.

Thanks for your patience! BR.

2021-11-11 13:06 UTC, auvipy approved these changes

2021-11-11 13:06 UTC, auvipy approved these changes

2021-11-11 15:29 UTC, merged